project:
  type: book

book:
  title: "STAT 8670 - Computational Methods in Statistics"
  author: "Chi-Kuang Yeh"
  date: today
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-optimization.qmd
    - 03-generating-rv.qmd
    - 04-monte-carlo.qmd
    - 05-cv.qmd
    - 06-resample.qmd
    - 07-smoothing.qmd
    - 08-density.qmd
    - part: "Appendix"
      chapters:
        - App_A-intro-R.qmd
        - App_B-distribution.qmd
        - App_C_Rpackage.qmd
        - APP_D_integration.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/chikuang/Teaching-Stat8670
        aria-label: GitHub
      - icon: file-pdf
        href: ./STAT-8670---Computational-Methods-in-Statistics.pdf
        aria-label: Download PDF

bibliography: references.bib

execute:
  cache: true
  freeze: auto

format:
  html:
    theme:
      - minty
      - brand
    css: custom-callouts.css
    filters:
      - addcalloutid.lua
    cache: true
  pdf:
    documentclass: scrreprt
    filters:
      - addcalloutid.lua
    cache: true

editor: visual